sudo: required

language: go

services:
  - docker

install:
  - docker build -t radio/valkyrie .
  - docker run -d -ti --rm --name=valkyrie radio/valkyrie

script:
  - docker exec valkyrie /bin/ash -c '! gofmt -d -s . 2>&1 | read'
  - docker exec valkyrie go vet ./...
  - docker exec valkyrie go test -v ./...