language: go

go:
  - master
  - 1.12.x
matrix:
  allow_failures:
    - go: master
  fast_finish: true

env:
- GO111MODULE=on # use go modules
cache:
  directories:
    - $HOME/gopath/pkg/mod/cache

install:
  - go mod download
script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go generate migrations/generate.go && git add migrations && git diff --cached --exit-code migrations
  - go vet ./...
  - go test -v -race ./...

addons:
  apt:
    sources:
      - trusty-media
    packages:
      - libmp3lame-dev
      - libmp3lame0
      - ffmpeg