# example configuration file, does not include options that have a default value
musicpath = "/path/to/music/dir"
templatedir = "/path/to/template/files"

[manager]
streamurl = "http://stream:80/mount.mp3"

[database]
# https://github.com/go-sql-driver/mysql#dsn-data-source-name for details
# it is required to pass param `parseTime=true` to the driver currently
DSN = "username:password@protocol(address)/dbname?param=value&parseTime=true"

[streamer]
streamurl = "http://username:password@stream:80/mount.mp3"

[irc]
server = "irc.rizon.net"
channels = ["#test"]
nick = "dev-valkyrie"