// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/radio.proto

package rpc // import "github.com/R-a-dio/valkyrie/rpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import _ "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Song struct {
	// song identifier (esong.id)
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// sha1 hexdigest of metadata contents
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// short metadata
	Metadata string `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// song length
	Length *duration.Duration `protobuf:"bytes,4,opt,name=length,proto3" json:"length,omitempty"`
	// last time this song was played
	LastPlayed *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_played,json=lastPlayed,proto3" json:"last_played,omitempty"`
	// DatabaseTrack fields
	TrackId       int32                `protobuf:"varint,16,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Artist        string               `protobuf:"bytes,17,opt,name=artist,proto3" json:"artist,omitempty"`
	Title         string               `protobuf:"bytes,18,opt,name=title,proto3" json:"title,omitempty"`
	Album         string               `protobuf:"bytes,19,opt,name=album,proto3" json:"album,omitempty"`
	FilePath      string               `protobuf:"bytes,20,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Tags          string               `protobuf:"bytes,21,opt,name=tags,proto3" json:"tags,omitempty"`
	Acceptor      string               `protobuf:"bytes,22,opt,name=acceptor,proto3" json:"acceptor,omitempty"`
	LastEditor    string               `protobuf:"bytes,23,opt,name=last_editor,json=lastEditor,proto3" json:"last_editor,omitempty"`
	Priority      int32                `protobuf:"varint,24,opt,name=priority,proto3" json:"priority,omitempty"`
	Usable        bool                 `protobuf:"varint,25,opt,name=usable,proto3" json:"usable,omitempty"`
	LastRequested *timestamp.Timestamp `protobuf:"bytes,26,opt,name=last_requested,json=lastRequested,proto3" json:"last_requested,omitempty"`
	RequestCount  int32                `protobuf:"varint,27,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	RequestDelay  *duration.Duration   `protobuf:"bytes,28,opt,name=request_delay,json=requestDelay,proto3" json:"request_delay,omitempty"`
	// the time the fields above were acquired from the database
	SyncTime             *timestamp.Timestamp `protobuf:"bytes,100,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Song) Reset()         { *m = Song{} }
func (m *Song) String() string { return proto.CompactTextString(m) }
func (*Song) ProtoMessage()    {}
func (*Song) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{0}
}
func (m *Song) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Song.Unmarshal(m, b)
}
func (m *Song) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Song.Marshal(b, m, deterministic)
}
func (dst *Song) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Song.Merge(dst, src)
}
func (m *Song) XXX_Size() int {
	return xxx_messageInfo_Song.Size(m)
}
func (m *Song) XXX_DiscardUnknown() {
	xxx_messageInfo_Song.DiscardUnknown(m)
}

var xxx_messageInfo_Song proto.InternalMessageInfo

func (m *Song) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Song) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Song) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *Song) GetLength() *duration.Duration {
	if m != nil {
		return m.Length
	}
	return nil
}

func (m *Song) GetLastPlayed() *timestamp.Timestamp {
	if m != nil {
		return m.LastPlayed
	}
	return nil
}

func (m *Song) GetTrackId() int32 {
	if m != nil {
		return m.TrackId
	}
	return 0
}

func (m *Song) GetArtist() string {
	if m != nil {
		return m.Artist
	}
	return ""
}

func (m *Song) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Song) GetAlbum() string {
	if m != nil {
		return m.Album
	}
	return ""
}

func (m *Song) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *Song) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Song) GetAcceptor() string {
	if m != nil {
		return m.Acceptor
	}
	return ""
}

func (m *Song) GetLastEditor() string {
	if m != nil {
		return m.LastEditor
	}
	return ""
}

func (m *Song) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Song) GetUsable() bool {
	if m != nil {
		return m.Usable
	}
	return false
}

func (m *Song) GetLastRequested() *timestamp.Timestamp {
	if m != nil {
		return m.LastRequested
	}
	return nil
}

func (m *Song) GetRequestCount() int32 {
	if m != nil {
		return m.RequestCount
	}
	return 0
}

func (m *Song) GetRequestDelay() *duration.Duration {
	if m != nil {
		return m.RequestDelay
	}
	return nil
}

func (m *Song) GetSyncTime() *timestamp.Timestamp {
	if m != nil {
		return m.SyncTime
	}
	return nil
}

type StatusResponse struct {
	// the current user that is streaming
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// the current song being played
	Song *Song `protobuf:"bytes,2,opt,name=song,proto3" json:"song,omitempty"`
	// information about the current song
	Info *SongInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	// information about the current listeners
	ListenerInfo *ListenerInfo `protobuf:"bytes,4,opt,name=listener_info,json=listenerInfo,proto3" json:"listener_info,omitempty"`
	// the current thread to be shown on the website or elsewhere
	Thread string `protobuf:"bytes,5,opt,name=thread,proto3" json:"thread,omitempty"`
	// the current configuration of the streamer
	StreamerConfig       *StreamerConfig `protobuf:"bytes,6,opt,name=streamer_config,json=streamerConfig,proto3" json:"streamer_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{1}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *StatusResponse) GetSong() *Song {
	if m != nil {
		return m.Song
	}
	return nil
}

func (m *StatusResponse) GetInfo() *SongInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *StatusResponse) GetListenerInfo() *ListenerInfo {
	if m != nil {
		return m.ListenerInfo
	}
	return nil
}

func (m *StatusResponse) GetThread() string {
	if m != nil {
		return m.Thread
	}
	return ""
}

func (m *StatusResponse) GetStreamerConfig() *StreamerConfig {
	if m != nil {
		return m.StreamerConfig
	}
	return nil
}

type SongUpdate struct {
	Song                 *Song     `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	Info                 *SongInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SongUpdate) Reset()         { *m = SongUpdate{} }
func (m *SongUpdate) String() string { return proto.CompactTextString(m) }
func (*SongUpdate) ProtoMessage()    {}
func (*SongUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{2}
}
func (m *SongUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongUpdate.Unmarshal(m, b)
}
func (m *SongUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongUpdate.Marshal(b, m, deterministic)
}
func (dst *SongUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongUpdate.Merge(dst, src)
}
func (m *SongUpdate) XXX_Size() int {
	return xxx_messageInfo_SongUpdate.Size(m)
}
func (m *SongUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_SongUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_SongUpdate proto.InternalMessageInfo

func (m *SongUpdate) GetSong() *Song {
	if m != nil {
		return m.Song
	}
	return nil
}

func (m *SongUpdate) GetInfo() *SongInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type SongInfo struct {
	// the time this song started playing
	StartTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// the time this song will end playing
	EndTime              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SongInfo) Reset()         { *m = SongInfo{} }
func (m *SongInfo) String() string { return proto.CompactTextString(m) }
func (*SongInfo) ProtoMessage()    {}
func (*SongInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{3}
}
func (m *SongInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongInfo.Unmarshal(m, b)
}
func (m *SongInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongInfo.Marshal(b, m, deterministic)
}
func (dst *SongInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongInfo.Merge(dst, src)
}
func (m *SongInfo) XXX_Size() int {
	return xxx_messageInfo_SongInfo.Size(m)
}
func (m *SongInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SongInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SongInfo proto.InternalMessageInfo

func (m *SongInfo) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *SongInfo) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type StreamerConfig struct {
	// can users request songs to be played right now
	RequestsEnabled bool `protobuf:"varint,1,opt,name=requests_enabled,json=requestsEnabled,proto3" json:"requests_enabled,omitempty"`
	// the queue implementation to use for the streamer
	QueueUsed            string   `protobuf:"bytes,2,opt,name=queue_used,json=queueUsed,proto3" json:"queue_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamerConfig) Reset()         { *m = StreamerConfig{} }
func (m *StreamerConfig) String() string { return proto.CompactTextString(m) }
func (*StreamerConfig) ProtoMessage()    {}
func (*StreamerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{4}
}
func (m *StreamerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamerConfig.Unmarshal(m, b)
}
func (m *StreamerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamerConfig.Marshal(b, m, deterministic)
}
func (dst *StreamerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamerConfig.Merge(dst, src)
}
func (m *StreamerConfig) XXX_Size() int {
	return xxx_messageInfo_StreamerConfig.Size(m)
}
func (m *StreamerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StreamerConfig proto.InternalMessageInfo

func (m *StreamerConfig) GetRequestsEnabled() bool {
	if m != nil {
		return m.RequestsEnabled
	}
	return false
}

func (m *StreamerConfig) GetQueueUsed() string {
	if m != nil {
		return m.QueueUsed
	}
	return ""
}

type User struct {
	// user identifier
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// user nickname, this is only a display-name
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// indicates if this user is a robot or not
	IsRobot              bool     `protobuf:"varint,3,opt,name=is_robot,json=isRobot,proto3" json:"is_robot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{5}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetIsRobot() bool {
	if m != nil {
		return m.IsRobot
	}
	return false
}

type ListenerInfo struct {
	// the amount of listeners to the stream
	Listeners            int64    `protobuf:"varint,1,opt,name=listeners,proto3" json:"listeners,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenerInfo) Reset()         { *m = ListenerInfo{} }
func (m *ListenerInfo) String() string { return proto.CompactTextString(m) }
func (*ListenerInfo) ProtoMessage()    {}
func (*ListenerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{6}
}
func (m *ListenerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenerInfo.Unmarshal(m, b)
}
func (m *ListenerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenerInfo.Marshal(b, m, deterministic)
}
func (dst *ListenerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenerInfo.Merge(dst, src)
}
func (m *ListenerInfo) XXX_Size() int {
	return xxx_messageInfo_ListenerInfo.Size(m)
}
func (m *ListenerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ListenerInfo proto.InternalMessageInfo

func (m *ListenerInfo) GetListeners() int64 {
	if m != nil {
		return m.Listeners
	}
	return 0
}

type SongAnnouncement struct {
	Song                 *Song         `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	Info                 *SongInfo     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	ListenerInfo         *ListenerInfo `protobuf:"bytes,3,opt,name=listener_info,json=listenerInfo,proto3" json:"listener_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SongAnnouncement) Reset()         { *m = SongAnnouncement{} }
func (m *SongAnnouncement) String() string { return proto.CompactTextString(m) }
func (*SongAnnouncement) ProtoMessage()    {}
func (*SongAnnouncement) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{7}
}
func (m *SongAnnouncement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongAnnouncement.Unmarshal(m, b)
}
func (m *SongAnnouncement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongAnnouncement.Marshal(b, m, deterministic)
}
func (dst *SongAnnouncement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongAnnouncement.Merge(dst, src)
}
func (m *SongAnnouncement) XXX_Size() int {
	return xxx_messageInfo_SongAnnouncement.Size(m)
}
func (m *SongAnnouncement) XXX_DiscardUnknown() {
	xxx_messageInfo_SongAnnouncement.DiscardUnknown(m)
}

var xxx_messageInfo_SongAnnouncement proto.InternalMessageInfo

func (m *SongAnnouncement) GetSong() *Song {
	if m != nil {
		return m.Song
	}
	return nil
}

func (m *SongAnnouncement) GetInfo() *SongInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *SongAnnouncement) GetListenerInfo() *ListenerInfo {
	if m != nil {
		return m.ListenerInfo
	}
	return nil
}

type SongRequestAnnouncement struct {
	Song                 *Song    `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SongRequestAnnouncement) Reset()         { *m = SongRequestAnnouncement{} }
func (m *SongRequestAnnouncement) String() string { return proto.CompactTextString(m) }
func (*SongRequestAnnouncement) ProtoMessage()    {}
func (*SongRequestAnnouncement) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{8}
}
func (m *SongRequestAnnouncement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongRequestAnnouncement.Unmarshal(m, b)
}
func (m *SongRequestAnnouncement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongRequestAnnouncement.Marshal(b, m, deterministic)
}
func (dst *SongRequestAnnouncement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongRequestAnnouncement.Merge(dst, src)
}
func (m *SongRequestAnnouncement) XXX_Size() int {
	return xxx_messageInfo_SongRequestAnnouncement.Size(m)
}
func (m *SongRequestAnnouncement) XXX_DiscardUnknown() {
	xxx_messageInfo_SongRequestAnnouncement.DiscardUnknown(m)
}

var xxx_messageInfo_SongRequestAnnouncement proto.InternalMessageInfo

func (m *SongRequestAnnouncement) GetSong() *Song {
	if m != nil {
		return m.Song
	}
	return nil
}

type StreamerResponse struct {
	UserError            *UserError `protobuf:"bytes,1,opt,name=user_error,json=userError,proto3" json:"user_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StreamerResponse) Reset()         { *m = StreamerResponse{} }
func (m *StreamerResponse) String() string { return proto.CompactTextString(m) }
func (*StreamerResponse) ProtoMessage()    {}
func (*StreamerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{9}
}
func (m *StreamerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamerResponse.Unmarshal(m, b)
}
func (m *StreamerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamerResponse.Marshal(b, m, deterministic)
}
func (dst *StreamerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamerResponse.Merge(dst, src)
}
func (m *StreamerResponse) XXX_Size() int {
	return xxx_messageInfo_StreamerResponse.Size(m)
}
func (m *StreamerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamerResponse proto.InternalMessageInfo

func (m *StreamerResponse) GetUserError() *UserError {
	if m != nil {
		return m.UserError
	}
	return nil
}

type QueueEntry struct {
	Song *Song `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	// is_user_request indicates if this was a request made by a human
	IsUserRequest bool `protobuf:"varint,2,opt,name=is_user_request,json=isUserRequest,proto3" json:"is_user_request,omitempty"`
	// user_identifier is the way we identify the user that added this to the
	// queue; This can be anything that uniquely identifies a user
	UserIdentifier string `protobuf:"bytes,3,opt,name=user_identifier,json=userIdentifier,proto3" json:"user_identifier,omitempty"`
	// expected_start_time is the expected time this song will start playing
	ExpectedStartTime    *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expected_start_time,json=expectedStartTime,proto3" json:"expected_start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueueEntry) Reset()         { *m = QueueEntry{} }
func (m *QueueEntry) String() string { return proto.CompactTextString(m) }
func (*QueueEntry) ProtoMessage()    {}
func (*QueueEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{10}
}
func (m *QueueEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueEntry.Unmarshal(m, b)
}
func (m *QueueEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueEntry.Marshal(b, m, deterministic)
}
func (dst *QueueEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueEntry.Merge(dst, src)
}
func (m *QueueEntry) XXX_Size() int {
	return xxx_messageInfo_QueueEntry.Size(m)
}
func (m *QueueEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueEntry.DiscardUnknown(m)
}

var xxx_messageInfo_QueueEntry proto.InternalMessageInfo

func (m *QueueEntry) GetSong() *Song {
	if m != nil {
		return m.Song
	}
	return nil
}

func (m *QueueEntry) GetIsUserRequest() bool {
	if m != nil {
		return m.IsUserRequest
	}
	return false
}

func (m *QueueEntry) GetUserIdentifier() string {
	if m != nil {
		return m.UserIdentifier
	}
	return ""
}

func (m *QueueEntry) GetExpectedStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExpectedStartTime
	}
	return nil
}

type QueueInfo struct {
	// the name of the queue implementation
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the entries in the queue
	Entries              []*QueueEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueueInfo) Reset()         { *m = QueueInfo{} }
func (m *QueueInfo) String() string { return proto.CompactTextString(m) }
func (*QueueInfo) ProtoMessage()    {}
func (*QueueInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{11}
}
func (m *QueueInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueInfo.Unmarshal(m, b)
}
func (m *QueueInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueInfo.Marshal(b, m, deterministic)
}
func (dst *QueueInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueInfo.Merge(dst, src)
}
func (m *QueueInfo) XXX_Size() int {
	return xxx_messageInfo_QueueInfo.Size(m)
}
func (m *QueueInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueInfo.DiscardUnknown(m)
}

var xxx_messageInfo_QueueInfo proto.InternalMessageInfo

func (m *QueueInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueueInfo) GetEntries() []*QueueEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type SongRequest struct {
	UserIdentifier       string   `protobuf:"bytes,1,opt,name=user_identifier,json=userIdentifier,proto3" json:"user_identifier,omitempty"`
	Song                 *Song    `protobuf:"bytes,2,opt,name=song,proto3" json:"song,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SongRequest) Reset()         { *m = SongRequest{} }
func (m *SongRequest) String() string { return proto.CompactTextString(m) }
func (*SongRequest) ProtoMessage()    {}
func (*SongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{12}
}
func (m *SongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongRequest.Unmarshal(m, b)
}
func (m *SongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongRequest.Marshal(b, m, deterministic)
}
func (dst *SongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongRequest.Merge(dst, src)
}
func (m *SongRequest) XXX_Size() int {
	return xxx_messageInfo_SongRequest.Size(m)
}
func (m *SongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SongRequest proto.InternalMessageInfo

func (m *SongRequest) GetUserIdentifier() string {
	if m != nil {
		return m.UserIdentifier
	}
	return ""
}

func (m *SongRequest) GetSong() *Song {
	if m != nil {
		return m.Song
	}
	return nil
}

type RequestResponse struct {
	Success              bool               `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UserDelay            *duration.Duration `protobuf:"bytes,3,opt,name=user_delay,json=userDelay,proto3" json:"user_delay,omitempty"`
	SongDelay            *duration.Duration `protobuf:"bytes,4,opt,name=song_delay,json=songDelay,proto3" json:"song_delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RequestResponse) Reset()         { *m = RequestResponse{} }
func (m *RequestResponse) String() string { return proto.CompactTextString(m) }
func (*RequestResponse) ProtoMessage()    {}
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{13}
}
func (m *RequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestResponse.Unmarshal(m, b)
}
func (m *RequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestResponse.Marshal(b, m, deterministic)
}
func (dst *RequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestResponse.Merge(dst, src)
}
func (m *RequestResponse) XXX_Size() int {
	return xxx_messageInfo_RequestResponse.Size(m)
}
func (m *RequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestResponse proto.InternalMessageInfo

func (m *RequestResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RequestResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RequestResponse) GetUserDelay() *duration.Duration {
	if m != nil {
		return m.UserDelay
	}
	return nil
}

func (m *RequestResponse) GetSongDelay() *duration.Duration {
	if m != nil {
		return m.SongDelay
	}
	return nil
}

// UserError is the protobuf variant of the UserError interface
type UserError struct {
	Public               bool     `protobuf:"varint,1,opt,name=public,proto3" json:"public,omitempty"`
	UserError            string   `protobuf:"bytes,2,opt,name=user_error,json=userError,proto3" json:"user_error,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserError) Reset()         { *m = UserError{} }
func (m *UserError) String() string { return proto.CompactTextString(m) }
func (*UserError) ProtoMessage()    {}
func (*UserError) Descriptor() ([]byte, []int) {
	return fileDescriptor_radio_129cacc6b95bb7f2, []int{14}
}
func (m *UserError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserError.Unmarshal(m, b)
}
func (m *UserError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserError.Marshal(b, m, deterministic)
}
func (dst *UserError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserError.Merge(dst, src)
}
func (m *UserError) XXX_Size() int {
	return xxx_messageInfo_UserError.Size(m)
}
func (m *UserError) XXX_DiscardUnknown() {
	xxx_messageInfo_UserError.DiscardUnknown(m)
}

var xxx_messageInfo_UserError proto.InternalMessageInfo

func (m *UserError) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *UserError) GetUserError() string {
	if m != nil {
		return m.UserError
	}
	return ""
}

func (m *UserError) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Song)(nil), "radio.Song")
	proto.RegisterType((*StatusResponse)(nil), "radio.StatusResponse")
	proto.RegisterType((*SongUpdate)(nil), "radio.SongUpdate")
	proto.RegisterType((*SongInfo)(nil), "radio.SongInfo")
	proto.RegisterType((*StreamerConfig)(nil), "radio.StreamerConfig")
	proto.RegisterType((*User)(nil), "radio.User")
	proto.RegisterType((*ListenerInfo)(nil), "radio.ListenerInfo")
	proto.RegisterType((*SongAnnouncement)(nil), "radio.SongAnnouncement")
	proto.RegisterType((*SongRequestAnnouncement)(nil), "radio.SongRequestAnnouncement")
	proto.RegisterType((*StreamerResponse)(nil), "radio.StreamerResponse")
	proto.RegisterType((*QueueEntry)(nil), "radio.QueueEntry")
	proto.RegisterType((*QueueInfo)(nil), "radio.QueueInfo")
	proto.RegisterType((*SongRequest)(nil), "radio.SongRequest")
	proto.RegisterType((*RequestResponse)(nil), "radio.RequestResponse")
	proto.RegisterType((*UserError)(nil), "radio.UserError")
}

func init() { proto.RegisterFile("rpc/radio.proto", fileDescriptor_radio_129cacc6b95bb7f2) }

var fileDescriptor_radio_129cacc6b95bb7f2 = []byte{
	// 1303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0x13, 0xc7,
	0x17, 0x97, 0xbf, 0x62, 0xfb, 0x38, 0x89, 0x9d, 0x01, 0x92, 0xc5, 0xf0, 0x27, 0xf9, 0x2f, 0x52,
	0x9b, 0xaa, 0xc5, 0x16, 0xa6, 0x15, 0x01, 0x24, 0xaa, 0x00, 0xb9, 0x48, 0x05, 0x15, 0x5d, 0x43,
	0x5b, 0x71, 0xb3, 0x1a, 0xef, 0x9e, 0xd8, 0x23, 0xd6, 0xbb, 0xcb, 0xcc, 0x2c, 0xc5, 0x52, 0x5f,
	0xa0, 0xb7, 0xbd, 0x69, 0xdf, 0xa1, 0x57, 0x7d, 0x8d, 0x3e, 0x49, 0xef, 0xfa, 0x0a, 0xd5, 0x7c,
	0xac, 0xb3, 0x89, 0x63, 0x4c, 0xab, 0xde, 0xed, 0xf9, 0x9a, 0x39, 0x1f, 0xbf, 0xf3, 0x9b, 0x85,
	0x36, 0x4f, 0x83, 0x3e, 0xa7, 0x21, 0x4b, 0x7a, 0x29, 0x4f, 0x64, 0x42, 0x6a, 0x5a, 0xe8, 0xde,
	0x18, 0x27, 0xc9, 0x38, 0xc2, 0xbe, 0x56, 0x8e, 0xb2, 0x93, 0x7e, 0x98, 0x71, 0x2a, 0x59, 0x12,
	0x1b, 0xb7, 0xee, 0xb5, 0xf3, 0x76, 0x9c, 0xa6, 0x72, 0x66, 0x8d, 0x0b, 0xc1, 0x3f, 0x70, 0x9a,
	0xa6, 0xc8, 0x85, 0xb5, 0xef, 0x9e, 0xb7, 0x4b, 0x36, 0x45, 0x21, 0xe9, 0x34, 0x35, 0x0e, 0xee,
	0xaf, 0x35, 0xa8, 0x0e, 0x93, 0x78, 0x4c, 0x36, 0xa1, 0xcc, 0x42, 0xa7, 0xb4, 0x57, 0xda, 0xaf,
	0x79, 0x65, 0x16, 0x12, 0x02, 0xd5, 0x09, 0x15, 0x13, 0xa7, 0xbc, 0x57, 0xda, 0x6f, 0x7a, 0xfa,
	0x9b, 0x74, 0xa1, 0x31, 0x45, 0x49, 0x43, 0x2a, 0xa9, 0x53, 0xd1, 0xfa, 0xb9, 0x4c, 0x6e, 0xc3,
	0x5a, 0x84, 0xf1, 0x58, 0x4e, 0x9c, 0xea, 0x5e, 0x69, 0xbf, 0x35, 0xb8, 0xda, 0x33, 0x57, 0xf7,
	0xf2, 0xab, 0x7b, 0x4f, 0x6c, 0x5d, 0x9e, 0x75, 0x24, 0x0f, 0xa0, 0x15, 0x51, 0x21, 0xfd, 0x34,
	0xa2, 0x33, 0x0c, 0x9d, 0x9a, 0x8e, 0xeb, 0x2e, 0xc4, 0xbd, 0xc8, 0x53, 0xf6, 0x40, 0xb9, 0x3f,
	0xd7, 0xde, 0xe4, 0x2a, 0x34, 0x24, 0xa7, 0xc1, 0x6b, 0x9f, 0x85, 0x4e, 0x47, 0x67, 0x5d, 0xd7,
	0xf2, 0x71, 0x48, 0xb6, 0x61, 0x8d, 0x72, 0xc9, 0x84, 0x74, 0xb6, 0x74, 0x92, 0x56, 0x22, 0x97,
	0xa1, 0x26, 0x99, 0x8c, 0xd0, 0x21, 0x5a, 0x6d, 0x04, 0xa5, 0xa5, 0xd1, 0x28, 0x9b, 0x3a, 0x97,
	0x8c, 0x56, 0x0b, 0xe4, 0x1a, 0x34, 0x4f, 0x58, 0x84, 0x7e, 0x4a, 0xe5, 0xc4, 0xb9, 0x6c, 0x6a,
	0x55, 0x8a, 0xe7, 0x54, 0x4e, 0x54, 0x6f, 0x24, 0x1d, 0x0b, 0xe7, 0x8a, 0xe9, 0x8d, 0xfa, 0x56,
	0xbd, 0xa1, 0x41, 0x80, 0xa9, 0x4c, 0xb8, 0xb3, 0x6d, 0xfc, 0x73, 0x99, 0xec, 0xda, 0x42, 0x31,
	0x64, 0xca, 0xbc, 0xa3, 0xcd, 0xba, 0x98, 0x23, 0xad, 0x51, 0xc1, 0x29, 0x67, 0x09, 0x67, 0x72,
	0xe6, 0x38, 0xba, 0x98, 0xb9, 0xac, 0xaa, 0xc9, 0x04, 0x1d, 0x45, 0xe8, 0x5c, 0xdd, 0x2b, 0xed,
	0x37, 0x3c, 0x2b, 0x91, 0x43, 0xd8, 0xd4, 0x87, 0x72, 0x7c, 0x93, 0xa1, 0x90, 0x18, 0x3a, 0xdd,
	0x95, 0x0d, 0xdc, 0x50, 0x11, 0x5e, 0x1e, 0x40, 0x6e, 0xc2, 0x86, 0x8d, 0xf6, 0x83, 0x24, 0x8b,
	0xa5, 0x73, 0x4d, 0xdf, 0xbd, 0x6e, 0x95, 0x8f, 0x95, 0x8e, 0x3c, 0x3c, 0x75, 0x0a, 0x31, 0xa2,
	0x33, 0xe7, 0xfa, 0xaa, 0xf9, 0xe6, 0xf1, 0x4f, 0x94, 0x3b, 0xb9, 0x0b, 0x4d, 0x31, 0x8b, 0x03,
	0x5f, 0x21, 0xcf, 0x09, 0x57, 0xa6, 0xd8, 0x50, 0xce, 0x4a, 0x74, 0x7f, 0x2a, 0xc3, 0xe6, 0x50,
	0x52, 0x99, 0x09, 0x0f, 0x45, 0x9a, 0xc4, 0x02, 0xc9, 0x2e, 0x54, 0x33, 0x81, 0x5c, 0xc3, 0xb4,
	0x35, 0x68, 0xf5, 0xcc, 0x3a, 0xbd, 0x14, 0xc8, 0x3d, 0x6d, 0x50, 0x0e, 0x22, 0x89, 0xc7, 0x1a,
	0xb5, 0xa7, 0x0e, 0x0a, 0xe0, 0x9e, 0x36, 0x90, 0x9b, 0x50, 0x65, 0xf1, 0x49, 0xa2, 0xe1, 0xdb,
	0x1a, 0xb4, 0x0b, 0x0e, 0xc7, 0xf1, 0x49, 0xe2, 0x69, 0x23, 0x39, 0x80, 0x8d, 0x88, 0x09, 0x89,
	0x31, 0x72, 0x5f, 0x7b, 0x1b, 0x48, 0x5f, 0xb2, 0xde, 0x4f, 0xad, 0x4d, 0x47, 0xac, 0x47, 0x05,
	0x49, 0x0d, 0x4b, 0x4e, 0x38, 0x52, 0x83, 0xe6, 0xa6, 0x67, 0x25, 0xf2, 0x10, 0xda, 0x42, 0x72,
	0xa4, 0x53, 0xe4, 0x7e, 0x90, 0xc4, 0x27, 0x6c, 0xec, 0xac, 0xe9, 0x33, 0xaf, 0xe4, 0x19, 0x58,
	0xeb, 0x63, 0x6d, 0xf4, 0x36, 0xc5, 0x19, 0xd9, 0xf5, 0x00, 0x54, 0x8e, 0x2f, 0xd3, 0x90, 0x4a,
	0x9c, 0x57, 0x59, 0x5a, 0x55, 0x65, 0xf9, 0x3d, 0x55, 0xba, 0x3f, 0x42, 0x23, 0xd7, 0x90, 0x7b,
	0x00, 0x42, 0x52, 0x2e, 0xcd, 0x94, 0x2a, 0x2b, 0xa7, 0xd4, 0xd4, 0xde, 0x4a, 0x26, 0x5f, 0x40,
	0x03, 0xe3, 0xd0, 0x04, 0x56, 0x57, 0x06, 0xd6, 0x31, 0x0e, 0xf5, 0x74, 0x5f, 0xa9, 0xe1, 0x16,
	0x6b, 0x24, 0x9f, 0x40, 0xc7, 0x02, 0x47, 0xf8, 0x18, 0x2b, 0x8c, 0x1b, 0x3e, 0x6a, 0x78, 0xed,
	0x5c, 0x7f, 0x64, 0xd4, 0xe4, 0x7f, 0x00, 0x6f, 0x32, 0xcc, 0xd0, 0xcf, 0x04, 0x86, 0x96, 0xa2,
	0x9a, 0x5a, 0xf3, 0x52, 0x60, 0xe8, 0x3e, 0x83, 0xaa, 0xc2, 0xc4, 0x02, 0xa7, 0x75, 0xa1, 0x11,
	0xb3, 0xe0, 0x75, 0x4c, 0xa7, 0x68, 0x83, 0xe6, 0xb2, 0xe2, 0x13, 0x26, 0x7c, 0x9e, 0x8c, 0x12,
	0xa9, 0xeb, 0x6f, 0x78, 0x75, 0x26, 0x3c, 0x25, 0xba, 0x9f, 0xc1, 0x7a, 0x71, 0xe4, 0xe4, 0x3a,
	0x34, 0xf3, 0xa1, 0x0b, 0x7d, 0x7a, 0xc5, 0x3b, 0x55, 0xb8, 0x3f, 0x97, 0xa0, 0xa3, 0xfa, 0x7a,
	0x18, 0xc7, 0x49, 0x16, 0x07, 0x38, 0xc5, 0x58, 0xfe, 0x37, 0x13, 0x5b, 0xc4, 0x65, 0xe5, 0x03,
	0x71, 0xe9, 0xde, 0x87, 0x1d, 0x7d, 0x99, 0xe9, 0xe3, 0x3f, 0x4a, 0xcd, 0x7d, 0x0c, 0x9d, 0x7c,
	0x52, 0xf3, 0x45, 0xec, 0x03, 0xa8, 0x7d, 0xf3, 0x91, 0xf3, 0x24, 0x5f, 0xc7, 0x4e, 0x61, 0x1d,
	0x8f, 0x94, 0xde, 0x6b, 0x66, 0xf9, 0xa7, 0xfb, 0x47, 0x09, 0xe0, 0x1b, 0x35, 0xa0, 0xa3, 0x58,
	0xf2, 0xd9, 0xea, 0x7e, 0x7c, 0x04, 0x6d, 0x26, 0x7c, 0x7d, 0x87, 0x1d, 0xbe, 0x6e, 0x4d, 0xc3,
	0xdb, 0x60, 0x42, 0xef, 0xbb, 0x51, 0x92, 0x8f, 0xa1, 0xad, 0x9d, 0x58, 0x88, 0xb1, 0x64, 0x27,
	0x0c, 0xb9, 0x7d, 0x99, 0x36, 0x95, 0xfa, 0x78, 0xae, 0x25, 0x5f, 0xc1, 0x25, 0x7c, 0x97, 0x62,
	0x20, 0x31, 0xf4, 0x0b, 0x50, 0x5f, 0x8d, 0xd8, 0xad, 0x3c, 0x6c, 0x98, 0x43, 0xde, 0x7d, 0x0a,
	0x4d, 0x5d, 0x8b, 0x46, 0x03, 0x81, 0xaa, 0x06, 0x54, 0xc9, 0x3c, 0x06, 0x1a, 0x4c, 0x9f, 0x42,
	0x1d, 0x63, 0xc9, 0x19, 0x0a, 0xa7, 0xbc, 0x57, 0xd9, 0x6f, 0x0d, 0xb6, 0x6c, 0x85, 0xa7, 0x2d,
	0xf0, 0x72, 0x0f, 0xf7, 0x3b, 0x68, 0x15, 0x66, 0x73, 0x51, 0x45, 0xa5, 0x0b, 0x2b, 0x5a, 0xc5,
	0x75, 0xee, 0xef, 0x25, 0x68, 0xdb, 0x53, 0xe7, 0x83, 0x73, 0xa0, 0x2e, 0xb2, 0x20, 0x40, 0x21,
	0xec, 0x6e, 0xe5, 0x22, 0xe9, 0x40, 0x65, 0x2a, 0xc6, 0x76, 0x2f, 0xd4, 0x27, 0x39, 0xb0, 0x43,
	0x36, 0xb4, 0x5f, 0x59, 0x45, 0xfb, 0x7a, 0xda, 0x86, 0xf3, 0x0f, 0x00, 0x54, 0x06, 0x36, 0x72,
	0xe5, 0x0f, 0x41, 0x53, 0x39, 0xeb, 0x48, 0xf7, 0x7b, 0x68, 0xce, 0xf1, 0xa3, 0xd8, 0x34, 0xcd,
	0x46, 0x11, 0x0b, 0x6c, 0xae, 0x56, 0x52, 0xeb, 0x5f, 0x40, 0x9f, 0x5d, 0xff, 0x39, 0xd6, 0xd4,
	0x8b, 0x6e, 0x2c, 0x06, 0x09, 0x46, 0x18, 0xfc, 0x55, 0x86, 0xfa, 0x33, 0x1a, 0xd3, 0x31, 0x72,
	0x72, 0x17, 0xd6, 0xcc, 0xcb, 0x42, 0xb6, 0x17, 0xb2, 0x3a, 0x52, 0xbf, 0x57, 0xdd, 0x53, 0x5e,
	0x3e, 0xf3, 0x00, 0xf5, 0xa0, 0x3e, 0x44, 0xa9, 0xc9, 0xa5, 0xf8, 0xfa, 0x74, 0x97, 0x1c, 0x43,
	0x3e, 0xd7, 0xfe, 0xfa, 0x07, 0x6b, 0xab, 0x30, 0x20, 0xc3, 0xe3, 0x4b, 0xa3, 0x1e, 0xc1, 0x96,
	0x8a, 0x3a, 0x4b, 0x8f, 0x17, 0xbf, 0x14, 0x4b, 0xcf, 0x38, 0x84, 0xe6, 0x10, 0xe5, 0x0b, 0xf3,
	0xfc, 0x5c, 0x5f, 0x70, 0x1a, 0x4a, 0xce, 0xe2, 0xf1, 0xb7, 0x34, 0xca, 0x96, 0xa7, 0xf1, 0x10,
	0xda, 0x43, 0x94, 0x67, 0xa8, 0xef, 0x22, 0xaa, 0x59, 0x16, 0x3f, 0xf8, 0xa5, 0x04, 0xcd, 0x9c,
	0x6a, 0x38, 0xf9, 0x12, 0xd6, 0x73, 0x41, 0xf7, 0x63, 0xa7, 0xd0, 0x8f, 0x22, 0x21, 0x2d, 0x4d,
	0xe7, 0x18, 0xda, 0xb9, 0x5f, 0xbe, 0x2b, 0x37, 0x8a, 0xa0, 0x5f, 0xe4, 0xb6, 0xa5, 0x99, 0xfd,
	0x56, 0x86, 0x46, 0xde, 0x47, 0x72, 0x00, 0x35, 0xbd, 0xda, 0x4b, 0xb1, 0xb0, 0x73, 0xae, 0xf3,
	0x73, 0x34, 0x3c, 0x80, 0xea, 0x50, 0x26, 0x29, 0x59, 0xa4, 0x8f, 0x47, 0x49, 0x12, 0x99, 0xe6,
	0x2e, 0x0d, 0xbe, 0x07, 0x2d, 0x9b, 0xb2, 0x6e, 0x07, 0x59, 0x2c, 0xa5, 0xbb, 0x6d, 0x75, 0xe7,
	0x97, 0xf8, 0xbe, 0x9e, 0xed, 0xbf, 0xc3, 0xc5, 0x6d, 0xa8, 0x69, 0x12, 0x5a, 0x5a, 0x6d, 0xa7,
	0x48, 0x55, 0x6a, 0xbe, 0x83, 0x3f, 0x4b, 0x79, 0xcc, 0x5d, 0x80, 0xc3, 0x30, 0xcc, 0xbb, 0xbf,
	0x48, 0x6a, 0x4b, 0x6f, 0x3d, 0x50, 0xc5, 0x0a, 0xe4, 0x6f, 0xf1, 0x6b, 0x7c, 0xb7, 0xbc, 0xd3,
	0x8b, 0x27, 0xaa, 0x55, 0xf5, 0x70, 0x9a, 0xbc, 0xc5, 0x8b, 0xae, 0x7b, 0x4f, 0xe3, 0xc9, 0x1d,
	0xa8, 0x1f, 0x19, 0x86, 0xfd, 0xf0, 0x52, 0x1f, 0xfd, 0xff, 0xd5, 0xee, 0x98, 0xc9, 0x49, 0x36,
	0xea, 0x05, 0xc9, 0xb4, 0xef, 0xdd, 0xa2, 0xb7, 0x42, 0x96, 0xf4, 0xdf, 0xd2, 0xe8, 0xf5, 0x8c,
	0x33, 0xec, 0xf3, 0x34, 0x18, 0xad, 0xe9, 0x43, 0xee, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xe2,
	0x28, 0x24, 0x40, 0xd0, 0x0d, 0x00, 0x00,
}
