// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: radio.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagerClient interface {
	Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	CurrentSong(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Manager_CurrentSongClient, error)
	UpdateSong(ctx context.Context, in *SongUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CurrentThread(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Manager_CurrentThreadClient, error)
	UpdateThread(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CurrentUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Manager_CurrentUserClient, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CurrentListenerCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Manager_CurrentListenerCountClient, error)
	UpdateListenerCount(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type managerClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerClient(cc grpc.ClientConnInterface) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/radio.Manager/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) CurrentSong(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Manager_CurrentSongClient, error) {
	stream, err := c.cc.NewStream(ctx, &Manager_ServiceDesc.Streams[0], "/radio.Manager/CurrentSong", opts...)
	if err != nil {
		return nil, err
	}
	x := &managerCurrentSongClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Manager_CurrentSongClient interface {
	Recv() (*SongUpdate, error)
	grpc.ClientStream
}

type managerCurrentSongClient struct {
	grpc.ClientStream
}

func (x *managerCurrentSongClient) Recv() (*SongUpdate, error) {
	m := new(SongUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *managerClient) UpdateSong(ctx context.Context, in *SongUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/radio.Manager/UpdateSong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) CurrentThread(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Manager_CurrentThreadClient, error) {
	stream, err := c.cc.NewStream(ctx, &Manager_ServiceDesc.Streams[1], "/radio.Manager/CurrentThread", opts...)
	if err != nil {
		return nil, err
	}
	x := &managerCurrentThreadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Manager_CurrentThreadClient interface {
	Recv() (*wrapperspb.StringValue, error)
	grpc.ClientStream
}

type managerCurrentThreadClient struct {
	grpc.ClientStream
}

func (x *managerCurrentThreadClient) Recv() (*wrapperspb.StringValue, error) {
	m := new(wrapperspb.StringValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *managerClient) UpdateThread(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/radio.Manager/UpdateThread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) CurrentUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Manager_CurrentUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &Manager_ServiceDesc.Streams[2], "/radio.Manager/CurrentUser", opts...)
	if err != nil {
		return nil, err
	}
	x := &managerCurrentUserClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Manager_CurrentUserClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type managerCurrentUserClient struct {
	grpc.ClientStream
}

func (x *managerCurrentUserClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *managerClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/radio.Manager/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) CurrentListenerCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Manager_CurrentListenerCountClient, error) {
	stream, err := c.cc.NewStream(ctx, &Manager_ServiceDesc.Streams[3], "/radio.Manager/CurrentListenerCount", opts...)
	if err != nil {
		return nil, err
	}
	x := &managerCurrentListenerCountClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Manager_CurrentListenerCountClient interface {
	Recv() (*wrapperspb.Int64Value, error)
	grpc.ClientStream
}

type managerCurrentListenerCountClient struct {
	grpc.ClientStream
}

func (x *managerCurrentListenerCountClient) Recv() (*wrapperspb.Int64Value, error) {
	m := new(wrapperspb.Int64Value)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *managerClient) UpdateListenerCount(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/radio.Manager/UpdateListenerCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
// All implementations must embed UnimplementedManagerServer
// for forward compatibility
type ManagerServer interface {
	Status(context.Context, *emptypb.Empty) (*StatusResponse, error)
	CurrentSong(*emptypb.Empty, Manager_CurrentSongServer) error
	UpdateSong(context.Context, *SongUpdate) (*emptypb.Empty, error)
	CurrentThread(*emptypb.Empty, Manager_CurrentThreadServer) error
	UpdateThread(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	CurrentUser(*emptypb.Empty, Manager_CurrentUserServer) error
	UpdateUser(context.Context, *User) (*emptypb.Empty, error)
	CurrentListenerCount(*emptypb.Empty, Manager_CurrentListenerCountServer) error
	UpdateListenerCount(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error)
	mustEmbedUnimplementedManagerServer()
}

// UnimplementedManagerServer must be embedded to have forward compatible implementations.
type UnimplementedManagerServer struct {
}

func (UnimplementedManagerServer) Status(context.Context, *emptypb.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedManagerServer) CurrentSong(*emptypb.Empty, Manager_CurrentSongServer) error {
	return status.Errorf(codes.Unimplemented, "method CurrentSong not implemented")
}
func (UnimplementedManagerServer) UpdateSong(context.Context, *SongUpdate) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSong not implemented")
}
func (UnimplementedManagerServer) CurrentThread(*emptypb.Empty, Manager_CurrentThreadServer) error {
	return status.Errorf(codes.Unimplemented, "method CurrentThread not implemented")
}
func (UnimplementedManagerServer) UpdateThread(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateThread not implemented")
}
func (UnimplementedManagerServer) CurrentUser(*emptypb.Empty, Manager_CurrentUserServer) error {
	return status.Errorf(codes.Unimplemented, "method CurrentUser not implemented")
}
func (UnimplementedManagerServer) UpdateUser(context.Context, *User) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedManagerServer) CurrentListenerCount(*emptypb.Empty, Manager_CurrentListenerCountServer) error {
	return status.Errorf(codes.Unimplemented, "method CurrentListenerCount not implemented")
}
func (UnimplementedManagerServer) UpdateListenerCount(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateListenerCount not implemented")
}
func (UnimplementedManagerServer) mustEmbedUnimplementedManagerServer() {}

// UnsafeManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServer will
// result in compilation errors.
type UnsafeManagerServer interface {
	mustEmbedUnimplementedManagerServer()
}

func RegisterManagerServer(s grpc.ServiceRegistrar, srv ManagerServer) {
	s.RegisterService(&Manager_ServiceDesc, srv)
}

func _Manager_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Manager/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Status(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_CurrentSong_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServer).CurrentSong(m, &managerCurrentSongServer{stream})
}

type Manager_CurrentSongServer interface {
	Send(*SongUpdate) error
	grpc.ServerStream
}

type managerCurrentSongServer struct {
	grpc.ServerStream
}

func (x *managerCurrentSongServer) Send(m *SongUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _Manager_UpdateSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).UpdateSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Manager/UpdateSong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).UpdateSong(ctx, req.(*SongUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_CurrentThread_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServer).CurrentThread(m, &managerCurrentThreadServer{stream})
}

type Manager_CurrentThreadServer interface {
	Send(*wrapperspb.StringValue) error
	grpc.ServerStream
}

type managerCurrentThreadServer struct {
	grpc.ServerStream
}

func (x *managerCurrentThreadServer) Send(m *wrapperspb.StringValue) error {
	return x.ServerStream.SendMsg(m)
}

func _Manager_UpdateThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).UpdateThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Manager/UpdateThread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).UpdateThread(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_CurrentUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServer).CurrentUser(m, &managerCurrentUserServer{stream})
}

type Manager_CurrentUserServer interface {
	Send(*User) error
	grpc.ServerStream
}

type managerCurrentUserServer struct {
	grpc.ServerStream
}

func (x *managerCurrentUserServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _Manager_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Manager/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_CurrentListenerCount_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServer).CurrentListenerCount(m, &managerCurrentListenerCountServer{stream})
}

type Manager_CurrentListenerCountServer interface {
	Send(*wrapperspb.Int64Value) error
	grpc.ServerStream
}

type managerCurrentListenerCountServer struct {
	grpc.ServerStream
}

func (x *managerCurrentListenerCountServer) Send(m *wrapperspb.Int64Value) error {
	return x.ServerStream.SendMsg(m)
}

func _Manager_UpdateListenerCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).UpdateListenerCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Manager/UpdateListenerCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).UpdateListenerCount(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

// Manager_ServiceDesc is the grpc.ServiceDesc for Manager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Manager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "radio.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Manager_Status_Handler,
		},
		{
			MethodName: "UpdateSong",
			Handler:    _Manager_UpdateSong_Handler,
		},
		{
			MethodName: "UpdateThread",
			Handler:    _Manager_UpdateThread_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Manager_UpdateUser_Handler,
		},
		{
			MethodName: "UpdateListenerCount",
			Handler:    _Manager_UpdateListenerCount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CurrentSong",
			Handler:       _Manager_CurrentSong_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CurrentThread",
			Handler:       _Manager_CurrentThread_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CurrentUser",
			Handler:       _Manager_CurrentUser_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CurrentListenerCount",
			Handler:       _Manager_CurrentListenerCount_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "radio.proto",
}

// AnnouncerClient is the client API for Announcer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnnouncerClient interface {
	AnnounceSong(ctx context.Context, in *SongAnnouncement, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AnnounceRequest(ctx context.Context, in *SongRequestAnnouncement, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type announcerClient struct {
	cc grpc.ClientConnInterface
}

func NewAnnouncerClient(cc grpc.ClientConnInterface) AnnouncerClient {
	return &announcerClient{cc}
}

func (c *announcerClient) AnnounceSong(ctx context.Context, in *SongAnnouncement, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/radio.Announcer/AnnounceSong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *announcerClient) AnnounceRequest(ctx context.Context, in *SongRequestAnnouncement, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/radio.Announcer/AnnounceRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnnouncerServer is the server API for Announcer service.
// All implementations must embed UnimplementedAnnouncerServer
// for forward compatibility
type AnnouncerServer interface {
	AnnounceSong(context.Context, *SongAnnouncement) (*emptypb.Empty, error)
	AnnounceRequest(context.Context, *SongRequestAnnouncement) (*emptypb.Empty, error)
	mustEmbedUnimplementedAnnouncerServer()
}

// UnimplementedAnnouncerServer must be embedded to have forward compatible implementations.
type UnimplementedAnnouncerServer struct {
}

func (UnimplementedAnnouncerServer) AnnounceSong(context.Context, *SongAnnouncement) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnnounceSong not implemented")
}
func (UnimplementedAnnouncerServer) AnnounceRequest(context.Context, *SongRequestAnnouncement) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnnounceRequest not implemented")
}
func (UnimplementedAnnouncerServer) mustEmbedUnimplementedAnnouncerServer() {}

// UnsafeAnnouncerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnnouncerServer will
// result in compilation errors.
type UnsafeAnnouncerServer interface {
	mustEmbedUnimplementedAnnouncerServer()
}

func RegisterAnnouncerServer(s grpc.ServiceRegistrar, srv AnnouncerServer) {
	s.RegisterService(&Announcer_ServiceDesc, srv)
}

func _Announcer_AnnounceSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongAnnouncement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnouncerServer).AnnounceSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Announcer/AnnounceSong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnouncerServer).AnnounceSong(ctx, req.(*SongAnnouncement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Announcer_AnnounceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongRequestAnnouncement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnouncerServer).AnnounceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Announcer/AnnounceRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnouncerServer).AnnounceRequest(ctx, req.(*SongRequestAnnouncement))
	}
	return interceptor(ctx, in, info, handler)
}

// Announcer_ServiceDesc is the grpc.ServiceDesc for Announcer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Announcer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "radio.Announcer",
	HandlerType: (*AnnouncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnnounceSong",
			Handler:    _Announcer_AnnounceSong_Handler,
		},
		{
			MethodName: "AnnounceRequest",
			Handler:    _Announcer_AnnounceRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "radio.proto",
}

// StreamerClient is the client API for Streamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamerClient interface {
	// Start starts the streamer
	Start(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StreamerResponse, error)
	// Stop stops the streamer, the boolean argument indicates if we should stop
	// right away, or wait until the current song ends
	Stop(ctx context.Context, in *wrapperspb.BoolValue, opts ...grpc.CallOption) (*StreamerResponse, error)
	// RequestSong requests a song to be played by the streamer
	RequestSong(ctx context.Context, in *SongRequest, opts ...grpc.CallOption) (*RequestResponse, error)
	// SetConfig changes the configuration of the streamer
	SetConfig(ctx context.Context, in *StreamerConfig, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Queue returns the current queue contents of the streamer
	Queue(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueueInfo, error)
}

type streamerClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamerClient(cc grpc.ClientConnInterface) StreamerClient {
	return &streamerClient{cc}
}

func (c *streamerClient) Start(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StreamerResponse, error) {
	out := new(StreamerResponse)
	err := c.cc.Invoke(ctx, "/radio.Streamer/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamerClient) Stop(ctx context.Context, in *wrapperspb.BoolValue, opts ...grpc.CallOption) (*StreamerResponse, error) {
	out := new(StreamerResponse)
	err := c.cc.Invoke(ctx, "/radio.Streamer/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamerClient) RequestSong(ctx context.Context, in *SongRequest, opts ...grpc.CallOption) (*RequestResponse, error) {
	out := new(RequestResponse)
	err := c.cc.Invoke(ctx, "/radio.Streamer/RequestSong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamerClient) SetConfig(ctx context.Context, in *StreamerConfig, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/radio.Streamer/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamerClient) Queue(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueueInfo, error) {
	out := new(QueueInfo)
	err := c.cc.Invoke(ctx, "/radio.Streamer/Queue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamerServer is the server API for Streamer service.
// All implementations must embed UnimplementedStreamerServer
// for forward compatibility
type StreamerServer interface {
	// Start starts the streamer
	Start(context.Context, *emptypb.Empty) (*StreamerResponse, error)
	// Stop stops the streamer, the boolean argument indicates if we should stop
	// right away, or wait until the current song ends
	Stop(context.Context, *wrapperspb.BoolValue) (*StreamerResponse, error)
	// RequestSong requests a song to be played by the streamer
	RequestSong(context.Context, *SongRequest) (*RequestResponse, error)
	// SetConfig changes the configuration of the streamer
	SetConfig(context.Context, *StreamerConfig) (*emptypb.Empty, error)
	// Queue returns the current queue contents of the streamer
	Queue(context.Context, *emptypb.Empty) (*QueueInfo, error)
	mustEmbedUnimplementedStreamerServer()
}

// UnimplementedStreamerServer must be embedded to have forward compatible implementations.
type UnimplementedStreamerServer struct {
}

func (UnimplementedStreamerServer) Start(context.Context, *emptypb.Empty) (*StreamerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedStreamerServer) Stop(context.Context, *wrapperspb.BoolValue) (*StreamerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedStreamerServer) RequestSong(context.Context, *SongRequest) (*RequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestSong not implemented")
}
func (UnimplementedStreamerServer) SetConfig(context.Context, *StreamerConfig) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedStreamerServer) Queue(context.Context, *emptypb.Empty) (*QueueInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Queue not implemented")
}
func (UnimplementedStreamerServer) mustEmbedUnimplementedStreamerServer() {}

// UnsafeStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamerServer will
// result in compilation errors.
type UnsafeStreamerServer interface {
	mustEmbedUnimplementedStreamerServer()
}

func RegisterStreamerServer(s grpc.ServiceRegistrar, srv StreamerServer) {
	s.RegisterService(&Streamer_ServiceDesc, srv)
}

func _Streamer_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Streamer/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamerServer).Start(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streamer_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.BoolValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Streamer/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamerServer).Stop(ctx, req.(*wrapperspb.BoolValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streamer_RequestSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamerServer).RequestSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Streamer/RequestSong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamerServer).RequestSong(ctx, req.(*SongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streamer_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamerConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamerServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Streamer/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamerServer).SetConfig(ctx, req.(*StreamerConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Streamer_Queue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamerServer).Queue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Streamer/Queue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamerServer).Queue(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Streamer_ServiceDesc is the grpc.ServiceDesc for Streamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Streamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "radio.Streamer",
	HandlerType: (*StreamerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Streamer_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Streamer_Stop_Handler,
		},
		{
			MethodName: "RequestSong",
			Handler:    _Streamer_RequestSong_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _Streamer_SetConfig_Handler,
		},
		{
			MethodName: "Queue",
			Handler:    _Streamer_Queue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "radio.proto",
}

// QueueClient is the client API for Queue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueueClient interface {
	AddRequest(ctx context.Context, in *QueueEntry, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReserveNext(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueueEntry, error)
	Remove(ctx context.Context, in *QueueEntry, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
	Entries(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueueInfo, error)
}

type queueClient struct {
	cc grpc.ClientConnInterface
}

func NewQueueClient(cc grpc.ClientConnInterface) QueueClient {
	return &queueClient{cc}
}

func (c *queueClient) AddRequest(ctx context.Context, in *QueueEntry, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/radio.Queue/AddRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) ReserveNext(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueueEntry, error) {
	out := new(QueueEntry)
	err := c.cc.Invoke(ctx, "/radio.Queue/ReserveNext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) Remove(ctx context.Context, in *QueueEntry, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, "/radio.Queue/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) Entries(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueueInfo, error) {
	out := new(QueueInfo)
	err := c.cc.Invoke(ctx, "/radio.Queue/Entries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueServer is the server API for Queue service.
// All implementations must embed UnimplementedQueueServer
// for forward compatibility
type QueueServer interface {
	AddRequest(context.Context, *QueueEntry) (*emptypb.Empty, error)
	ReserveNext(context.Context, *emptypb.Empty) (*QueueEntry, error)
	Remove(context.Context, *QueueEntry) (*wrapperspb.BoolValue, error)
	Entries(context.Context, *emptypb.Empty) (*QueueInfo, error)
	mustEmbedUnimplementedQueueServer()
}

// UnimplementedQueueServer must be embedded to have forward compatible implementations.
type UnimplementedQueueServer struct {
}

func (UnimplementedQueueServer) AddRequest(context.Context, *QueueEntry) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRequest not implemented")
}
func (UnimplementedQueueServer) ReserveNext(context.Context, *emptypb.Empty) (*QueueEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveNext not implemented")
}
func (UnimplementedQueueServer) Remove(context.Context, *QueueEntry) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedQueueServer) Entries(context.Context, *emptypb.Empty) (*QueueInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Entries not implemented")
}
func (UnimplementedQueueServer) mustEmbedUnimplementedQueueServer() {}

// UnsafeQueueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueueServer will
// result in compilation errors.
type UnsafeQueueServer interface {
	mustEmbedUnimplementedQueueServer()
}

func RegisterQueueServer(s grpc.ServiceRegistrar, srv QueueServer) {
	s.RegisterService(&Queue_ServiceDesc, srv)
}

func _Queue_AddRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).AddRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Queue/AddRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).AddRequest(ctx, req.(*QueueEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_ReserveNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).ReserveNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Queue/ReserveNext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).ReserveNext(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Queue/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).Remove(ctx, req.(*QueueEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_Entries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).Entries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radio.Queue/Entries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).Entries(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Queue_ServiceDesc is the grpc.ServiceDesc for Queue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Queue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "radio.Queue",
	HandlerType: (*QueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRequest",
			Handler:    _Queue_AddRequest_Handler,
		},
		{
			MethodName: "ReserveNext",
			Handler:    _Queue_ReserveNext_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Queue_Remove_Handler,
		},
		{
			MethodName: "Entries",
			Handler:    _Queue_Entries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "radio.proto",
}
