// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/streamer.proto

package rpc // import "github.com/R-a-dio/valkyrie/rpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StopRequest struct {
	ForceStop            bool     `protobuf:"varint,1,opt,name=force_stop,json=forceStop" json:"force_stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_12f047193863a991, []int{0}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (dst *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(dst, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

func (m *StopRequest) GetForceStop() bool {
	if m != nil {
		return m.ForceStop
	}
	return false
}

type QueueEntry struct {
	// is_request indicates if this was a request made by a human
	IsRequest bool `protobuf:"varint,1,opt,name=is_request,json=isRequest" json:"is_request,omitempty"`
	// user_identifier is the way we identify the user that added this to the
	// queue; This can be anything that uniquely identifies a user
	UserIdentifier string `protobuf:"bytes,2,opt,name=user_identifier,json=userIdentifier" json:"user_identifier,omitempty"`
	// estimated_play_time is the estimated time for this track to be played
	EstimatedPlayTime string `protobuf:"bytes,3,opt,name=estimated_play_time,json=estimatedPlayTime" json:"estimated_play_time,omitempty"`
	// track_id is the id used in the database table
	TrackId int64 `protobuf:"varint,4,opt,name=track_id,json=trackId" json:"track_id,omitempty"`
	// track_tags is a short `artist - title` field
	TrackTags            string   `protobuf:"bytes,5,opt,name=track_tags,json=trackTags" json:"track_tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueEntry) Reset()         { *m = QueueEntry{} }
func (m *QueueEntry) String() string { return proto.CompactTextString(m) }
func (*QueueEntry) ProtoMessage()    {}
func (*QueueEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_12f047193863a991, []int{1}
}
func (m *QueueEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueEntry.Unmarshal(m, b)
}
func (m *QueueEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueEntry.Marshal(b, m, deterministic)
}
func (dst *QueueEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueEntry.Merge(dst, src)
}
func (m *QueueEntry) XXX_Size() int {
	return xxx_messageInfo_QueueEntry.Size(m)
}
func (m *QueueEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueEntry.DiscardUnknown(m)
}

var xxx_messageInfo_QueueEntry proto.InternalMessageInfo

func (m *QueueEntry) GetIsRequest() bool {
	if m != nil {
		return m.IsRequest
	}
	return false
}

func (m *QueueEntry) GetUserIdentifier() string {
	if m != nil {
		return m.UserIdentifier
	}
	return ""
}

func (m *QueueEntry) GetEstimatedPlayTime() string {
	if m != nil {
		return m.EstimatedPlayTime
	}
	return ""
}

func (m *QueueEntry) GetTrackId() int64 {
	if m != nil {
		return m.TrackId
	}
	return 0
}

func (m *QueueEntry) GetTrackTags() string {
	if m != nil {
		return m.TrackTags
	}
	return ""
}

type TrackRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Track                int64    `protobuf:"varint,2,opt,name=track" json:"track,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackRequest) Reset()         { *m = TrackRequest{} }
func (m *TrackRequest) String() string { return proto.CompactTextString(m) }
func (*TrackRequest) ProtoMessage()    {}
func (*TrackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_12f047193863a991, []int{2}
}
func (m *TrackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackRequest.Unmarshal(m, b)
}
func (m *TrackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackRequest.Marshal(b, m, deterministic)
}
func (dst *TrackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackRequest.Merge(dst, src)
}
func (m *TrackRequest) XXX_Size() int {
	return xxx_messageInfo_TrackRequest.Size(m)
}
func (m *TrackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrackRequest proto.InternalMessageInfo

func (m *TrackRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *TrackRequest) GetTrack() int64 {
	if m != nil {
		return m.Track
	}
	return 0
}

type RequestResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestResponse) Reset()         { *m = RequestResponse{} }
func (m *RequestResponse) String() string { return proto.CompactTextString(m) }
func (*RequestResponse) ProtoMessage()    {}
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_12f047193863a991, []int{3}
}
func (m *RequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestResponse.Unmarshal(m, b)
}
func (m *RequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestResponse.Marshal(b, m, deterministic)
}
func (dst *RequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestResponse.Merge(dst, src)
}
func (m *RequestResponse) XXX_Size() int {
	return xxx_messageInfo_RequestResponse.Size(m)
}
func (m *RequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestResponse proto.InternalMessageInfo

func (m *RequestResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RequestResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*StopRequest)(nil), "radio.rpc.StopRequest")
	proto.RegisterType((*QueueEntry)(nil), "radio.rpc.QueueEntry")
	proto.RegisterType((*TrackRequest)(nil), "radio.rpc.TrackRequest")
	proto.RegisterType((*RequestResponse)(nil), "radio.rpc.RequestResponse")
}

func init() { proto.RegisterFile("rpc/streamer.proto", fileDescriptor_streamer_12f047193863a991) }

var fileDescriptor_streamer_12f047193863a991 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x49, 0x43, 0x93, 0xa1, 0x6a, 0x60, 0x41, 0x60, 0x22, 0x01, 0x21, 0x17, 0x82, 0x44,
	0x6d, 0xa9, 0x9c, 0xb9, 0x14, 0x38, 0xf4, 0x82, 0xc0, 0xc9, 0x89, 0x8b, 0xb5, 0x59, 0x4f, 0xc3,
	0xaa, 0x76, 0x76, 0xd9, 0x19, 0x23, 0xf9, 0xe5, 0x78, 0x15, 0x5e, 0x05, 0xed, 0xda, 0x8e, 0xdc,
	0xe6, 0xe6, 0xef, 0x67, 0x46, 0xdf, 0xec, 0x67, 0x10, 0xce, 0xaa, 0x94, 0xd8, 0xa1, 0xac, 0xd0,
	0x25, 0xd6, 0x19, 0x36, 0x62, 0xea, 0x64, 0xa1, 0x4d, 0xe2, 0xac, 0x9a, 0xcf, 0xbc, 0xcc, 0x8d,
	0x45, 0x6a, 0xb5, 0xe5, 0x07, 0x78, 0xb4, 0x66, 0x63, 0x33, 0xfc, 0x5d, 0x23, 0xb1, 0x78, 0x05,
	0x70, 0x63, 0x9c, 0xc2, 0x9c, 0xd8, 0xd8, 0x38, 0x5a, 0x44, 0xab, 0x49, 0x36, 0x0d, 0x8c, 0x77,
	0x2d, 0xff, 0x46, 0x00, 0x3f, 0x6a, 0xac, 0xf1, 0xeb, 0x9e, 0x5d, 0xe3, 0xdd, 0x9a, 0x72, 0xd7,
	0xce, 0xf6, 0x6e, 0x4d, 0xfd, 0xb2, 0x77, 0x30, 0xab, 0x09, 0x5d, 0xae, 0x0b, 0xdc, 0xb3, 0xbe,
	0xd1, 0xe8, 0xe2, 0x07, 0x8b, 0x68, 0x35, 0xcd, 0xce, 0x3d, 0x7d, 0x7d, 0x60, 0x45, 0x02, 0x4f,
	0x91, 0x58, 0x57, 0x92, 0xb1, 0xc8, 0x6d, 0x29, 0x9b, 0x9c, 0x75, 0x85, 0xf1, 0x28, 0x98, 0x9f,
	0x1c, 0xa4, 0xef, 0xa5, 0x6c, 0x36, 0xba, 0x42, 0xf1, 0x12, 0x26, 0xec, 0xa4, 0xba, 0xcd, 0x75,
	0x11, 0x9f, 0x2c, 0xa2, 0xd5, 0x28, 0x3b, 0x0d, 0xf8, 0xba, 0xf0, 0x91, 0x5a, 0x89, 0xe5, 0x8e,
	0xe2, 0x71, 0xd8, 0x30, 0x0d, 0xcc, 0x46, 0xee, 0x68, 0xf9, 0x05, 0xce, 0x36, 0x1e, 0xf4, 0x11,
	0x5f, 0x03, 0x0c, 0xd2, 0x45, 0xc1, 0x3e, 0x60, 0xc4, 0x33, 0x18, 0x87, 0xe1, 0x10, 0x7c, 0x94,
	0xb5, 0x60, 0xf9, 0x09, 0x66, 0xdd, 0x82, 0x0c, 0xc9, 0x9a, 0x3d, 0xa1, 0x88, 0xe1, 0x94, 0x6a,
	0xa5, 0x90, 0xa8, 0x7b, 0x87, 0x1e, 0x8a, 0xc7, 0x30, 0xaa, 0x68, 0xd7, 0x5d, 0xee, 0x3f, 0x2f,
	0xff, 0x45, 0x30, 0x59, 0x77, 0x15, 0x89, 0xf7, 0x30, 0x5e, 0xb3, 0x74, 0x2c, 0x66, 0xc9, 0xa1,
	0xa6, 0xe4, 0x5b, 0x5d, 0x96, 0xf3, 0xfb, 0x84, 0x48, 0xe1, 0xc4, 0xb7, 0x20, 0x9e, 0x0f, 0x84,
	0x41, 0x79, 0xc7, 0x03, 0x9f, 0xe1, 0xac, 0xd3, 0xc2, 0xd1, 0xe2, 0xc5, 0xc0, 0x30, 0x7c, 0x86,
	0xf9, 0x7c, 0x20, 0xdc, 0xbf, 0xec, 0x12, 0xce, 0xd7, 0xc8, 0x1d, 0x2b, 0xb7, 0x25, 0xde, 0x49,
	0x7a, 0x65, 0xcc, 0x71, 0xd2, 0xab, 0xb7, 0x3f, 0xdf, 0xec, 0x34, 0xff, 0xaa, 0xb7, 0x89, 0x32,
	0x55, 0x9a, 0x5d, 0xc8, 0x8b, 0x42, 0x9b, 0xf4, 0x8f, 0x2c, 0x6f, 0x1b, 0xa7, 0x31, 0x75, 0x56,
	0x6d, 0x1f, 0x86, 0xff, 0xef, 0xe3, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xe5, 0x4f, 0x3c,
	0xb1, 0x02, 0x00, 0x00,
}
