// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/streamer/streamer.proto

package streamer // import "github.com/R-a-dio/valkyrie/rpc/streamer"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_f2dde099f6b45b80, []int{0}
}
func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (dst *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(dst, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type Bool struct {
	Bool                 bool     `protobuf:"varint,1,opt,name=bool" json:"bool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_f2dde099f6b45b80, []int{1}
}
func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (dst *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(dst, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

type StopRequest struct {
	ForceStop            bool     `protobuf:"varint,1,opt,name=force_stop,json=forceStop" json:"force_stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_f2dde099f6b45b80, []int{2}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (dst *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(dst, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

func (m *StopRequest) GetForceStop() bool {
	if m != nil {
		return m.ForceStop
	}
	return false
}

type QueueEntry struct {
	// is_request indicates if this was a request made by a human
	IsRequest bool `protobuf:"varint,1,opt,name=is_request,json=isRequest" json:"is_request,omitempty"`
	// user_identifier is the way we identify the user that added this to the
	// queue; This can be anything that uniquely identifies a user
	UserIdentifier string `protobuf:"bytes,2,opt,name=user_identifier,json=userIdentifier" json:"user_identifier,omitempty"`
	// estimated_play_time is the estimated time for this track to be played
	EstimatedPlayTime string `protobuf:"bytes,3,opt,name=estimated_play_time,json=estimatedPlayTime" json:"estimated_play_time,omitempty"`
	// track_id is the id used in the database table
	TrackId int64 `protobuf:"varint,4,opt,name=track_id,json=trackId" json:"track_id,omitempty"`
	// track_tags is a short `artist - title` field
	TrackTags            string   `protobuf:"bytes,5,opt,name=track_tags,json=trackTags" json:"track_tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueEntry) Reset()         { *m = QueueEntry{} }
func (m *QueueEntry) String() string { return proto.CompactTextString(m) }
func (*QueueEntry) ProtoMessage()    {}
func (*QueueEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_f2dde099f6b45b80, []int{3}
}
func (m *QueueEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueEntry.Unmarshal(m, b)
}
func (m *QueueEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueEntry.Marshal(b, m, deterministic)
}
func (dst *QueueEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueEntry.Merge(dst, src)
}
func (m *QueueEntry) XXX_Size() int {
	return xxx_messageInfo_QueueEntry.Size(m)
}
func (m *QueueEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueEntry.DiscardUnknown(m)
}

var xxx_messageInfo_QueueEntry proto.InternalMessageInfo

func (m *QueueEntry) GetIsRequest() bool {
	if m != nil {
		return m.IsRequest
	}
	return false
}

func (m *QueueEntry) GetUserIdentifier() string {
	if m != nil {
		return m.UserIdentifier
	}
	return ""
}

func (m *QueueEntry) GetEstimatedPlayTime() string {
	if m != nil {
		return m.EstimatedPlayTime
	}
	return ""
}

func (m *QueueEntry) GetTrackId() int64 {
	if m != nil {
		return m.TrackId
	}
	return 0
}

func (m *QueueEntry) GetTrackTags() string {
	if m != nil {
		return m.TrackTags
	}
	return ""
}

type StatusResponse struct {
	Running              bool          `protobuf:"varint,1,opt,name=running" json:"running,omitempty"`
	Queue                []*QueueEntry `protobuf:"bytes,2,rep,name=queue" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_f2dde099f6b45b80, []int{4}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *StatusResponse) GetQueue() []*QueueEntry {
	if m != nil {
		return m.Queue
	}
	return nil
}

type TrackRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Track                int64    `protobuf:"varint,2,opt,name=track" json:"track,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackRequest) Reset()         { *m = TrackRequest{} }
func (m *TrackRequest) String() string { return proto.CompactTextString(m) }
func (*TrackRequest) ProtoMessage()    {}
func (*TrackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_f2dde099f6b45b80, []int{5}
}
func (m *TrackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackRequest.Unmarshal(m, b)
}
func (m *TrackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackRequest.Marshal(b, m, deterministic)
}
func (dst *TrackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackRequest.Merge(dst, src)
}
func (m *TrackRequest) XXX_Size() int {
	return xxx_messageInfo_TrackRequest.Size(m)
}
func (m *TrackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrackRequest proto.InternalMessageInfo

func (m *TrackRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *TrackRequest) GetTrack() int64 {
	if m != nil {
		return m.Track
	}
	return 0
}

type RequestResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestResponse) Reset()         { *m = RequestResponse{} }
func (m *RequestResponse) String() string { return proto.CompactTextString(m) }
func (*RequestResponse) ProtoMessage()    {}
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_streamer_f2dde099f6b45b80, []int{6}
}
func (m *RequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestResponse.Unmarshal(m, b)
}
func (m *RequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestResponse.Marshal(b, m, deterministic)
}
func (dst *RequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestResponse.Merge(dst, src)
}
func (m *RequestResponse) XXX_Size() int {
	return xxx_messageInfo_RequestResponse.Size(m)
}
func (m *RequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestResponse proto.InternalMessageInfo

func (m *RequestResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RequestResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Null)(nil), "radio.internal.streamer.Null")
	proto.RegisterType((*Bool)(nil), "radio.internal.streamer.Bool")
	proto.RegisterType((*StopRequest)(nil), "radio.internal.streamer.StopRequest")
	proto.RegisterType((*QueueEntry)(nil), "radio.internal.streamer.QueueEntry")
	proto.RegisterType((*StatusResponse)(nil), "radio.internal.streamer.StatusResponse")
	proto.RegisterType((*TrackRequest)(nil), "radio.internal.streamer.TrackRequest")
	proto.RegisterType((*RequestResponse)(nil), "radio.internal.streamer.RequestResponse")
}

func init() {
	proto.RegisterFile("rpc/streamer/streamer.proto", fileDescriptor_streamer_f2dde099f6b45b80)
}

var fileDescriptor_streamer_f2dde099f6b45b80 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x6b, 0x27, 0x4d, 0xa6, 0x55, 0x0a, 0x0b, 0x12, 0x26, 0xa8, 0x28, 0x32, 0xa0, 0x5a,
	0x88, 0x3a, 0x52, 0x39, 0x71, 0xe0, 0x52, 0xd1, 0x43, 0x85, 0x54, 0x15, 0x3b, 0x27, 0x2e, 0xd6,
	0xc6, 0x9e, 0x9a, 0x55, 0x6d, 0xaf, 0xb3, 0xbb, 0x46, 0xca, 0xe7, 0xf0, 0x23, 0x7c, 0x1b, 0xda,
	0xb5, 0x1d, 0x0c, 0x92, 0x93, 0xdb, 0xce, 0x9b, 0xb7, 0xb3, 0x6f, 0xdf, 0xcc, 0xc0, 0x2b, 0x51,
	0x25, 0x4b, 0xa9, 0x04, 0xd2, 0x02, 0xc5, 0xee, 0x10, 0x54, 0x82, 0x2b, 0x4e, 0x5e, 0x08, 0x9a,
	0x32, 0x1e, 0xb0, 0x52, 0xa1, 0x28, 0x69, 0x1e, 0x74, 0x69, 0x6f, 0x0c, 0xce, 0x5d, 0x9d, 0xe7,
	0xde, 0x1c, 0x9c, 0x6b, 0xce, 0x73, 0x42, 0xc0, 0x59, 0x73, 0x9e, 0xbb, 0xd6, 0xc2, 0xf2, 0x27,
	0xa1, 0x39, 0x7b, 0x1f, 0xe0, 0x24, 0x52, 0xbc, 0x0a, 0x71, 0x53, 0xa3, 0x54, 0xe4, 0x1c, 0xe0,
	0x81, 0x8b, 0x04, 0x63, 0xa9, 0x78, 0xd5, 0x12, 0xa7, 0x06, 0xd1, 0x2c, 0xef, 0xb7, 0x05, 0xf0,
	0xad, 0xc6, 0x1a, 0x6f, 0x4a, 0x25, 0xb6, 0x9a, 0xcd, 0x64, 0x2c, 0x9a, 0xbb, 0x1d, 0x9b, 0xc9,
	0xae, 0xd8, 0x05, 0x9c, 0xd5, 0x12, 0x45, 0xcc, 0x52, 0x2c, 0x15, 0x7b, 0x60, 0x28, 0xdc, 0xa3,
	0x85, 0xe5, 0x4f, 0xc3, 0x99, 0x86, 0x6f, 0x77, 0x28, 0x09, 0xe0, 0x19, 0x4a, 0xc5, 0x0a, 0xaa,
	0x30, 0x8d, 0xab, 0x9c, 0x6e, 0x63, 0xc5, 0x0a, 0x74, 0x6d, 0x43, 0x7e, 0xba, 0x4b, 0xdd, 0xe7,
	0x74, 0xbb, 0x62, 0x05, 0x92, 0x97, 0x30, 0x51, 0x82, 0x26, 0x8f, 0x31, 0x4b, 0x5d, 0x67, 0x61,
	0xf9, 0x76, 0x78, 0x6c, 0xe2, 0xdb, 0x54, 0x4b, 0x6a, 0x52, 0x8a, 0x66, 0xd2, 0x1d, 0x99, 0x0a,
	0x53, 0x83, 0xac, 0x68, 0x26, 0x3d, 0x84, 0x59, 0xa4, 0xa8, 0xaa, 0x65, 0x88, 0xb2, 0xe2, 0xa5,
	0x44, 0xe2, 0xc2, 0xb1, 0xa8, 0xcb, 0x92, 0x95, 0x59, 0xfb, 0x81, 0x2e, 0x24, 0x9f, 0x60, 0xb4,
	0xd1, 0x7f, 0x75, 0x8f, 0x16, 0xb6, 0x7f, 0x72, 0xf5, 0x26, 0x18, 0xf0, 0x39, 0xf8, 0xeb, 0x48,
	0xd8, 0xdc, 0xf0, 0xbe, 0xc0, 0xe9, 0x4a, 0xbf, 0xd9, 0x39, 0xf1, 0x1a, 0xa0, 0x67, 0x82, 0x65,
	0x54, 0xf5, 0x10, 0xf2, 0x1c, 0x46, 0x46, 0xa3, 0xf1, 0xc7, 0x0e, 0x9b, 0xc0, 0xfb, 0x0c, 0x67,
	0x6d, 0x81, 0xbe, 0x5a, 0x59, 0x27, 0x09, 0x4a, 0xd9, 0xa9, 0x6d, 0x43, 0xf2, 0x04, 0xec, 0x42,
	0x66, 0xad, 0xc1, 0xfa, 0x78, 0xf5, 0xcb, 0x86, 0x49, 0xd4, 0x6a, 0x24, 0x37, 0x30, 0x8a, 0x14,
	0x15, 0x8a, 0x9c, 0x0f, 0x7e, 0x43, 0xcf, 0xca, 0x7c, 0x7f, 0x9a, 0x7c, 0x05, 0x47, 0x0f, 0x02,
	0x79, 0x3b, 0x48, 0xeb, 0x4d, 0xd3, 0xa1, 0x62, 0xf7, 0x30, 0x6e, 0x9a, 0x71, 0x48, 0xd4, 0xc5,
	0x9e, 0xd7, 0xfe, 0x69, 0x66, 0x0c, 0xa7, 0xed, 0xdb, 0xc6, 0x7e, 0xf2, 0x6e, 0xf0, 0x62, 0xbf,
	0x3d, 0x73, 0x7f, 0x90, 0xf6, 0xbf, 0xff, 0x77, 0x30, 0x8b, 0x50, 0xb5, 0x28, 0x5d, 0xe7, 0xb8,
	0x47, 0xba, 0xde, 0xb9, 0x03, 0x16, 0x5c, 0xbf, 0xff, 0xee, 0x67, 0x4c, 0xfd, 0xa8, 0xd7, 0x41,
	0xc2, 0x8b, 0x65, 0x78, 0x49, 0x2f, 0x53, 0xc6, 0x97, 0x3f, 0x69, 0xfe, 0xb8, 0x15, 0x0c, 0x97,
	0xfd, 0xb5, 0x5f, 0x8f, 0xcd, 0xba, 0x7f, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x48, 0xef, 0xd9,
	0xd1, 0x0d, 0x04, 0x00, 0x00,
}
