CREATE TABLE "relays" (
  "name" VARCHAR(64) NOT NULL,
  "status" TEXT NOT NULL,
  "stream" TEXT NOT NULL,
  "online" BOOLEAN NOT NULL DEFAULT FALSE,
  "disabled" BOOLEAN NOT NULL DEFAULT FALSE,
  "noredir" BOOLEAN NOT NULL DEFAULT FALSE,
  "listeners" INTEGER NOT NULL DEFAULT 0,
  "max" INTEGER NOT NULL DEFAULT 0,
  "err" TEXT NOT NULL DEFAULT '',
  PRIMARY KEY ("name")
);
