name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install apt-get dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libmp3lame-dev

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Install go tooling
      run: |
        go install github.com/matryer/moq@latest
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Generate
      run: go generate

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
